{% set name = "factor-analyzer" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/factor_analyzer-{{ version }}.tar.gz
  sha256: 87c24617197688675cd443b8205bf2b232eb3583d0a99be49d9826ac2476411d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy
    - pandas
    - pre-commit
    - python
    - scikit-learn
    - scipy

test:
  imports:
    - factor_analyzer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/EducationalTestingService/factor_analyzer
  summary: A Factor Analysis tool written in Python
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://factor-analyzer.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/EducationalTestingService/factor_analyzer

extra:
  recipe-maintainers:
    - melonhead901
